#!/usr/bin/env python
from __future__ import print_function

import os


def count_files_in_directory(d):
    num_files = 0
    for root, dirs, files in os.walk(d):
        num_files += len(files)
    return num_files


def subdirs(dir):
    paths = (os.path.join(dir, name) for name in os.listdir(dir))
    return [path for path in paths if os.path.isdir(path) and not os.path.islink(path)]

if __name__ == '__main__':
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else '.'
    pairs = []
    total = 0
    for subdir in subdirs(root):
        print(subdir, ' ', end='', flush=True)
        this = count_files_in_directory(subdir)
        print(this, flush=True)
        pairs.append((this, subdir))
        total += this
    print('\n\n')
    pairs.sort()
    for count, subdir in pairs:
        print('{:7d} {}'.format(count, subdir))
    print("\nTotal", total)
